-- Noor e Ramadan - Dhikr Collection Seed Data
-- Common Dhikr with recommended counts
-- Execute this in Supabase SQL Editor after running schema.sql

INSERT INTO dhikr_collection (
  title_bangla,
  title_english,
  title_arabic,
  dhikr_text_arabic,
  bangla_transliteration,
  english_transliteration,
  translation_bangla,
  translation_english,
  count_recommendation,
  category_bangla,
  category_english,
  benefits_bangla,
  benefits_english,
  reference_bangla,
  reference_english
) VALUES

('তাসবীহ - সুবহানাল্লাহ', 'Glorification - SubhanAllah', 'تَسْبِيحُ سُبْحَانَ اللهِ',
'سُبْحَانَ اللهِ',
'সুবহানাল্লাহ',
'SubhanAllah',
'আল্লাহ পবিত্র',
'Glory be to Allah',
33,
'তাসবীহ',
'Glorification',
'প্রতিটি তাসবীহে জান্নাতে একটি গাছ রোপণ হয়, গুনাহ মাফ হয়',
'A tree is planted in Paradise for each glorification, sins are forgiven',
'সহীহ মুসলিম',
'Sahih Muslim'),

('তাহমীদ - আলহামদুলিল্লাহ', 'Praise - Alhamdulillah', 'حَمْدُ الْحَمْدُ لِلَّهِ',
'الْحَمْدُ لِلَّهِ',
'আলহামদুলিল্লাহ',
'Alhamdulillah',
'সমস্ত প্রশংসা আল্লাহর জন্য',
'All praise is to Allah',
33,
'তাহমীদ',
'Praise',
'নিয়ামতের কৃতজ্ঞতা, আল্লাহর সন্তুষ্টি লাভ',
'Gratitude for blessings, attaining Allah''s pleasure',
'সহীহ মুসলিম',
'Sahih Muslim'),

('তাকবীর - আল্লাহু আকবার', 'Takbir - Allahu Akbar', 'تَكْبِيرُ اللهُ أَكْبَرُ',
'اللهُ أَكْبَرُ',
'আল্লাহু আকবার',
'Allahu Akbar',
'আল্লাহ সবচেয়ে বড়',
'Allah is the Greatest',
34,
'তাকবীর',
'Takbir',
'আল্লাহর মহত্ত্ব স্বীকার, সওয়াব বৃদ্ধি',
'Acknowledging Allah''s greatness, increase in rewards',
'সহীহ মুসলিম',
'Sahih Muslim'),

('লা ইলাহা ইল্লাল্লাহ', 'La Ilaha Illallah', 'لَا إِلَهَ إِلَّا اللهُ',
'لَا إِلَهَ إِلَّا اللهُ',
'লা ইলাহা ইল্লাল্লাহ',
'La ilaha illallah',
'আল্লাহ ছাড়া কোন ইলাহ নেই',
'There is no deity except Allah',
100,
'তাওহীদ',
'Tawhid',
'ঈমান শক্তিশালী হয়, অন্তর পরিশুদ্ধ হয়, জান্নাতের চাবি',
'Faith strengthens, heart purifies, key to Paradise',
'সহীহ মুসলিম, তিরমিযী',
'Sahih Muslim, Tirmidhi'),

('লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু', 'Complete Tawhid', 'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ',
'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
'লা ইলাহা ইল্লাল্লাহু ওয়াহদাহু লা শারীকা লাহু, লাহুল মুলকু ওয়া লাহুল হামদু ওয়া হুওয়া আলা কুল্লি শাইইন ক্বাদীর',
'La ilaha illallahu wahdahu la sharika lahu, lahul-mulku wa lahul-hamdu wa huwa ''ala kulli shay''in qadeer',
'আল্লাহ ছাড়া কোন ইলাহ নেই, তিনি একক, তাঁর কোন শরীক নেই, রাজত্ব তাঁরই এবং সকল প্রশংসা তাঁরই আর তিনি সব কিছুর উপর ক্ষমতাবান',
'There is no deity except Allah alone, He has no partner, His is the dominion and His is the praise, and He is over all things competent',
10,
'তাওহীদ',
'Tawhid',
'১০ বার পড়লে একটি দাস মুক্তির সমান সওয়াব, ১০০ নেকি, ১০০ গুনাহ মাফ',
'10 times equals freeing a slave, 100 good deeds, 100 sins forgiven',
'সহীহ বুখারী, সহীহ মুসলিম',
'Sahih Bukhari, Sahih Muslim'),

('আস্তাগফিরুল্লাহ', 'Seeking Forgiveness', 'أَسْتَغْفِرُ اللهَ',
'أَسْتَغْفِرُ اللهَ وَأَتُوبُ إِلَيْهِ',
'আস্তাগফিরুল্লাহা ওয়া আতূবু ইলাইহি',
'Astaghfirullaha wa atubu ilayhi',
'আমি আল্লাহর কাছে ক্ষমা চাই এবং তাঁর দিকে ফিরে আসি',
'I seek Allah''s forgiveness and turn to Him in repentance',
100,
'ইস্তিগফার',
'Repentance',
'সকল গুনাহ মাফ, অন্তর পরিশুদ্ধ, রিযিক বৃদ্ধি',
'All sins forgiven, heart purified, increase in provisions',
'সহীহ বুখারী',
'Sahih Bukhari'),

('সাইয়িদুল ইস্তিগফার', 'Master of Seeking Forgiveness', 'سَيِّدُ الاِسْتِغْفَارِ',
'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ',
'আল্লাহুম্মা আনতা রাব্বি লা ইলাহা ইল্লা আনতা, খালাক্বতানি ওয়া আনা আবদুকা, ওয়া আনা আলা আহদিকা ওয়া ওয়াদিকা মাস্তাতা''তু',
'Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana ''abduka, wa ana ''ala ''ahdika wa wa''dika ma istata''tu',
'হে আল্লাহ! তুমি আমার রব, তুমি ছাড়া কোন ইলাহ নেই। তুমি আমাকে সৃষ্টি করেছ এবং আমি তোমার বান্দা। আমি সাধ্যমত তোমার সাথে প্রতিশ্রুতি ও অঙ্গীকারে অটল আছি',
'O Allah, You are my Lord, there is no deity except You. You created me and I am Your servant, and I am on Your covenant and promise as much as I can',
1,
'ইস্তিগফার',
'Repentance',
'সকালে পড়লে সন্ধ্যার আগে মৃত্যু হলে জান্নাতে যাবে। সব গুনাহ মাফ।',
'If recited in morning and die before evening, will enter Paradise. All sins forgiven.',
'সহীহ বুখারী',
'Sahih Bukhari'),

('দরূদ শরীফ', 'Blessings upon Prophet', 'الصَّلَاةُ عَلَى النَّبِيِّ',
'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ',
'আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিও ওয়া আলা আলি মুহাম্মাদ',
'Allahumma salli ''ala Muhammadin wa ''ala ali Muhammad',
'হে আল্লাহ! মুহাম্মদ ও তাঁর বংশধরদের উপর রহমত বর্ষণ করুন',
'O Allah, send blessings upon Muhammad and his family',
10,
'দরূদ',
'Salawat',
'১ বার দরূদে ১০ বার আল্লাহ রহমত বর্ষণ করেন। নবীজির শাফাআত লাভ।',
'For 1 Durood, Allah sends 10 mercies. Intercession of the Prophet.',
'সহীহ মুসলিম',
'Sahih Muslim'),

('লা হাওলা ওয়ালা কুওয়াতা', 'No Power Except Allah', 'لَا حَوْلَ وَلَا قُوَّةَ',
'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ',
'লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ',
'La hawla wa la quwwata illa billah',
'আল্লাহ ছাড়া কোন শক্তি ও ক্ষমতা নেই',
'There is no power or strength except with Allah',
7,
'যিকির',
'Dhikr',
'জান্নাতের ভাণ্ডারের চাবি। সকল সমস্যার সমাধান।',
'Key to treasures of Paradise. Solution to all problems.',
'সহীহ বুখারী, সহীহ মুসলিম',
'Sahih Bukhari, Sahih Muslim'),

('সুবহানাল্লাহিল আযীম', 'Glory to Allah the Magnificent', 'سُبْحَانَ اللهِ الْعَظِيمِ',
'سُبْحَانَ اللهِ الْعَظِيمِ وَبِحَمْدِهِ',
'সুবহানাল্লাহিল আযীমি ওয়া বিহামদিহি',
'Subhanallahil-''Azim wa bihamdih',
'মহান আল্লাহ পবিত্র এবং তাঁর প্রশংসা',
'Glory be to Allah the Magnificent and praise Him',
10,
'তাসবীহ',
'Glorification',
'অল্প পরিশ্রমে অধিক সওয়াব। মিযানে ভারী।',
'Great reward with little effort. Heavy in the scale of deeds.',
'সহীহ বুখারী, সহীহ মুসলিম',
'Sahih Bukhari, Sahih Muslim');

-- Verify insertion
SELECT category_english, COUNT(*) as dhikr_count 
FROM dhikr_collection 
GROUP BY category_english;

SELECT COUNT(*) as total_dhikr FROM dhikr_collection;
