-- Noor e Ramadan - Duas Collection Seed Data
-- 20+ Authentic Duas with Arabic, Bangla & English
-- Execute this in Supabase SQL Editor after running schema.sql

INSERT INTO duas (
  title_bangla, 
  title_english, 
  title_arabic,
  category_bangla, 
  category_english,
  dua_arabic,
  dua_bangla_transliteration,
  dua_english_transliteration,
  translation_bangla,
  translation_english,
  reference_bangla,
  reference_english,
  benefits_bangla,
  benefits_english,
  display_order
) VALUES

-- DAILY LIFE DUAS
('খাওয়ার আগে', 'Before Eating', 'دُعَاءُ قَبْلَ الطَّعَامِ', 'দৈনন্দিন জীবন', 'Daily Life',
'بِسْمِ اللهِ وَعَلَى بَرَكَةِ اللهِ',
'বিসমিল্লাহি ওয়া আলা বারাকাতিল্লাহ',
'Bismillahi wa ala barakatillah',
'আল্লাহর নামে এবং আল্লাহর বরকতের উপর (শুরু করছি)',
'In the name of Allah and with the blessings of Allah',
'আবু দাউদ, ইবনে মাজাহ',
'Abu Dawud, Ibn Majah',
'খাদ্যে বরকত হয়, শয়তান শরীক হতে পারে না',
'Blessings in food, Satan cannot partake',
1),

('খাওয়ার পরে', 'After Eating', 'دُعَاءُ بَعْدَ الطَّعَامِ', 'দৈনন্দিন জীবন', 'Daily Life',
'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
'আলহামদুলিল্লাহিল্লাযী আতআমানা ওয়া সাক্বানা ওয়া জাআলানা মুসলিমীন',
'Alhamdulillahil-ladhi at''amana wa saqana wa ja''alana muslimin',
'সমস্ত প্রশংসা আল্লাহর জন্য যিনি আমাদের খাওয়ালেন, পান করালেন এবং মুসলিম বানালেন',
'All praise is to Allah who fed us, gave us drink, and made us Muslims',
'আবু দাউদ, তিরমিযী',
'Abu Dawud, Tirmidhi',
'কৃতজ্ঞতা প্রকাশ করা, নিয়ামতের শুকরিয়া',
'Expressing gratitude, thanking for blessings',
2),

('ঘুমানোর আগে', 'Before Sleeping', 'دُعَاءُ قَبْلَ النَّوْمِ', 'দৈনন্দিন জীবন', 'Daily Life',
'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
'বিসমিকা আল্লাহুম্মা আমূতু ওয়া আহইয়া',
'Bismika Allahumma amutu wa ahya',
'হে আল্লাহ! তোমার নামে আমি মরি এবং বাঁচি',
'O Allah, in Your name I die and I live',
'সহীহ বুখারী',
'Sahih Bukhari',
'নিরাপদ ঘুম, ফেরেশতা হেফাজত করে',
'Safe sleep, angels protect',
3),

('ঘুম থেকে ওঠার পর', 'Upon Waking Up', 'دُعَاءُ الاِسْتِيقَاظِ', 'দৈনন্দিন জীবন', 'Daily Life',
'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
'আলহামদুলিল্লাহিল্লাযী আহইয়ানা বাদা মা আমাতানা ওয়া ইলাইহিন নুশুর',
'Alhamdulillahil-ladhi ahyana ba''da ma amatana wa ilaihin-nushur',
'সমস্ত প্রশংসা আল্লাহর যিনি আমাদের মৃত্যুর পর জীবিত করলেন এবং তাঁর দিকেই প্রত্যাবর্তন',
'All praise to Allah who gave us life after death and to Him is the return',
'সহীহ বুখারী',
'Sahih Bukhari',
'জীবন ফিরে পাওয়ার শুকরিয়া, দিন শুরু হয় আল্লাহর স্মরণে',
'Gratitude for life, day begins with remembrance of Allah',
4),

('বাড়ি থেকে বের হওয়ার সময়', 'When Leaving Home', 'دُعَاءُ الخُرُوجِ مِنَ البَيْتِ', 'দৈনন্দিন জীবন', 'Daily Life',
'بِسْمِ اللهِ تَوَكَّلْتُ عَلَى اللهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ',
'বিসমিল্লাহি তাওয়াক্কালতু আলাল্লাহি লা হাওলা ওয়ালা কুওয়াতা ইল্লা বিল্লাহ',
'Bismillahi tawakkaltu ''alallahi la hawla wa la quwwata illa billah',
'আল্লাহর নামে, আল্লাহর উপর ভরসা করলাম, আল্লাহ ছাড়া কোন শক্তি ও ক্ষমতা নেই',
'In the name of Allah, I trust in Allah, there is no power or strength except with Allah',
'আবু দাউদ, তিরমিযী',
'Abu Dawud, Tirmidhi',
'নিরাপত্তা, শয়তান দূরে থাকে, পথ সহজ হয়',
'Safety, Satan stays away, path becomes easy',
5),

('বাড়িতে প্রবেশের সময়', 'When Entering Home', 'دُعَاءُ دُخُولِ البَيْتِ', 'দৈনন্দিন জীবন', 'Daily Life',
'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلَجِ وَخَيْرَ الْمَخْرَجِ بِسْمِ اللهِ وَلَجْنَا وَبِسْمِ اللهِ خَرَجْنَا وَعَلَى اللهِ رَبِّنَا تَوَكَّلْنَا',
'আল্লাহুম্মা ইন্নি আসআলুকা খাইরাল মাওলাজি ওয়া খাইরাল মাখরাজি বিসমিল্লাহি ওয়ালাজনা ওয়া বিসমিল্লাহি খারাজনা ওয়া আলাল্লাহি রাব্বিনা তাওয়াক্কালনা',
'Allahumma inni as''aluka khayral-mawlaji wa khayral-makhraji bismillahi walajna wa bismillahi kharajna wa ''alallahi rabbina tawakkalna',
'হে আল্লাহ! আমি তোমার কাছে উত্তম প্রবেশ ও উত্তম বের হওয়ার প্রার্থনা করছি। আল্লাহর নামে প্রবেশ করলাম, আল্লাহর নামে বের হলাম এবং আমাদের রব আল্লাহর উপর ভরসা করলাম',
'O Allah, I ask You for the best entering and the best exiting. In the name of Allah we enter, in the name of Allah we exit, and upon Allah our Lord we rely',
'আবু দাউদ',
'Abu Dawud',
'ঘরে বরকত, পরিবারে শান্তি',
'Blessings in home, peace in family',
6),

-- PRAYER DUAS
('নামাজ শুরুর দোয়া', 'Opening Prayer', 'دُعَاءُ الاِسْتِفْتَاحِ', 'নামাজ', 'Prayer',
'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلَهَ غَيْرُكَ',
'সুবহানাকা আল্লাহুম্মা ওয়া বিহামদিকা ওয়া তাবারাকাসমুকা ওয়া তাআলা জাদ্দুকা ওয়ালা ইলাহা গাইরুক',
'Subhanaka Allahumma wa bihamdika wa tabarakasmuka wa ta''ala jadduka wa la ilaha ghayruk',
'হে আল্লাহ! তুমি পবিত্র, তোমার প্রশংসা, তোমার নাম বরকতময়, তোমার মর্যাদা সুউচ্চ এবং তুমি ছাড়া কোন ইলাহ নেই',
'Glory be to You O Allah, and praise. Blessed is Your name, exalted is Your majesty, and there is no deity except You',
'আবু দাউদ, তিরমিযী',
'Abu Dawud, Tirmidhi',
'নামাজে মনোনিবেশ, খুশু বৃদ্ধি',
'Concentration in prayer, increase in khushu',
7),

('রুকুতে', 'In Ruku', 'دُعَاءُ الرُّكُوعِ', 'নামাজ', 'Prayer',
'سُبْحَانَ رَبِّيَ الْعَظِيمِ',
'সুবহানা রাব্বিয়াল আযীম',
'Subhana Rabbiyal Azim',
'আমার মহান রবের পবিত্রতা ঘোষণা করছি',
'Glory be to my Lord, the Most Great',
'সহীহ মুসলিম',
'Sahih Muslim',
'নামাজের ফরজ অংশ, আল্লাহর মহত্ত্বের স্বীকৃতি',
'Obligatory part of prayer, acknowledging Allah''s greatness',
8),

('সিজদায়', 'In Sujood', 'دُعَاءُ السُّجُودِ', 'নামাজ', 'Prayer',
'سُبْحَانَ رَبِّيَ الْأَعْلَى',
'সুবহানা রাব্বিয়াল আ''লা',
'Subhana Rabbiyal A''la',
'আমার সর্বোচ্চ রবের পবিত্রতা ঘোষণা করছি',
'Glory be to my Lord, the Most High',
'সহীহ মুসলিম',
'Sahih Muslim',
'সিজদার ফরজ যিকির, বান্দা আল্লাহর সবচেয়ে নিকটবর্তী হয়',
'Obligatory remembrance in prostration, closest to Allah',
9),

('দুই সিজদার মাঝে', 'Between Two Sujood', 'دُعَاءُ بَيْنَ السَّجْدَتَيْنِ', 'নামাজ', 'Prayer',
'رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي',
'রাব্বিগফির লি, রাব্বিগফির লি',
'Rabbighfir li, Rabbighfir li',
'হে আমার রব! আমাকে ক্ষমা করুন, হে আমার রব! আমাকে ক্ষমা করুন',
'O my Lord, forgive me. O my Lord, forgive me',
'আবু দাউদ, ইবনে মাজাহ',
'Abu Dawud, Ibn Majah',
'গুনাহ মাফ, আল্লাহর রহমত লাভ',
'Forgiveness of sins, attaining Allah''s mercy',
10),

-- MORNING & EVENING DUAS
('সকালের দোয়া - আয়াতুল কুরসি', 'Morning - Ayatul Kursi', 'آيَةُ الْكُرْسِيِّ', 'সকাল-সন্ধ্যা', 'Morning/Evening',
'اللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ',
'আল্লাহু লা ইলাহা ইল্লা হুওয়াল হাইয়্যুল কাইয়্যুম, লা তা''খুযুহু সিনাতুও ওয়ালা নাউম',
'Allahu la ilaha illa Huwal-Hayyul-Qayyum, la ta''khudhuhu sinatun wa la nawm',
'আল্লাহ, তিনি ছাড়া কোন ইলাহ নেই, তিনি চিরঞ্জীব, সর্বসত্তার ধারক। তাঁকে তন্দ্রাও স্পর্শ করে না এবং নিদ্রাও নয়',
'Allah - there is no deity except Him, the Ever-Living, the Sustainer. Neither drowsiness overtakes Him nor sleep',
'সূরা বাকারা ২:২৫৫',
'Surah Al-Baqarah 2:255',
'সকালে পড়লে সন্ধ্যা পর্যন্ত হেফাজত, প্রতিটি ক্ষতি থেকে রক্ষা',
'Protection till evening, safety from all harm',
11),

('সকালের দোয়া - তাসবীহ', 'Morning Dhikr', 'تَسْبِيحُ الصَّبَاحِ', 'সকাল-সন্ধ্যা', 'Morning/Evening',
'سُبْحَانَ اللهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ',
'সুবহানাল্লাহি ওয়া বিহামদিহি আদাদা খালক্বিহি ওয়া রিদা নাফসিহি ওয়া যিনাতা আরশিহি ওয়া মিদাদা কালিমাতিহ',
'Subhanallahi wa bihamdihi ''adada khalqihi wa rida nafsihi wa zinata ''arshihi wa midada kalimatih',
'আল্লাহ পবিত্র এবং তাঁর প্রশংসা, তাঁর সৃষ্টির সংখ্যায়, তাঁর সন্তুষ্টির পরিমাণে, তাঁর আরশের ওজনে এবং তাঁর কালিমার কালির পরিমাণে',
'Glory be to Allah and praise Him, by the number of His creation, by His pleasure, by the weight of His Throne, and by the ink of His words',
'সহীহ মুসলিম',
'Sahih Muslim',
'অসংখ্য সওয়াব, তাসবীহের সহজ পদ্ধতি',
'Countless rewards, easy method of glorification',
12),

-- PROTECTION DUAS
('বিপদ থেকে রক্ষা', 'Protection from Calamity', 'دُعَاءُ الْبَلَاءِ', 'সুরক্ষা', 'Protection',
'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
'হাসবুনাল্লাহু ওয়া নি''মাল ওয়াকীল',
'Hasbunallahu wa ni''mal wakil',
'আল্লাহই আমাদের জন্য যথেষ্ট এবং তিনি কত উত্তম কর্মবিধায়ক',
'Allah is sufficient for us, and He is the best Disposer of affairs',
'সহীহ বুখারী, সূরা আল-ইমরান ৩:১৭৩',
'Sahih Bukhari, Surah Ali Imran 3:173',
'ভয় দূর হয়, আল্লাহর সাহায্য আসে, সকল বিপদ থেকে রক্ষা',
'Fear dissipates, Allah''s help comes, protection from all calamities',
13),

('বদনজর থেকে রক্ষা', 'Protection from Evil Eye', 'دُعَاءُ الْعَيْنِ', 'সুরক্ষা', 'Protection',
'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
'আউযু বিকালিমাতিল্লাহিত তাম্মাতি মিন শাররি মা খালাক',
'A''udhu bikalimatillahit-tammati min sharri ma khalaq',
'আল্লাহর পরিপূর্ণ কালিমাসমূহের মাধ্যমে তাঁর সৃষ্ট সকল অনিষ্ট থেকে আশ্রয় প্রার্থনা করছি',
'I seek refuge in the perfect words of Allah from the evil of what He has created',
'সহীহ মুসলিম',
'Sahih Muslim',
'বদনজর, জাদু, হিংসা থেকে রক্ষা পায়',
'Protection from evil eye, magic, and jealousy',
14),

-- GRATITUDE DUAS
('আল্লাহর প্রশংসা', 'Praise of Allah', 'حَمْدُ اللهِ', 'কৃতজ্ঞতা', 'Gratitude',
'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
'আলহামদুলিল্লাহি রাব্বিল আলামীন',
'Alhamdulillahi Rabbil-''alamin',
'সমস্ত প্রশংসা আল্লাহর জন্য যিনি সকল জগতের রব',
'All praise is due to Allah, Lord of all the worlds',
'সূরা ফাতিহা ১:২',
'Surah Al-Fatihah 1:2',
'প্রতিটি কাজে বরকত, কৃতজ্ঞতা প্রকাশ',
'Blessings in every deed, expressing gratitude',
15),

('সর্বদা বলার দোয়া', 'Constant Remembrance', 'ذِكْرٌ دَائِمٌ', 'কৃতজ্ঞতা', 'Gratitude',
'سُبْحَانَ اللهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللهُ وَاللهُ أَكْبَرُ',
'সুবহানাল্লাহ ওয়াল হামদুলিল্লাহ ওয়ালা ইলাহা ইল্লাল্লাহু ওয়াল্লাহু আকবার',
'Subhanallah walhamdulillah wa la ilaha illallahu wallahu akbar',
'আল্লাহ পবিত্র, সমস্ত প্রশংসা আল্লাহর, আল্লাহ ছাড়া কোন ইলাহ নেই এবং আল্লাহ সবচেয়ে বড়',
'Glory be to Allah, all praise is to Allah, there is no deity except Allah, and Allah is the Greatest',
'সহীহ মুসলিম',
'Sahih Muslim',
'প্রতিটি তাসবীহে ১টি করে গাছ জান্নাতে রোপণ হয়',
'For each glorification, a tree is planted in Paradise',
16),

-- RAMADAN SPECIAL
('ইফতারের দোয়া', 'Breaking Fast', 'دُعَاءُ الإِفْطَارِ', 'রমজান', 'Ramadan',
'اللَّهُمَّ إِنِّي لَكَ صُمْتُ وَبِكَ آمَنْتُ وَعَلَيْكَ تَوَكَّلْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ',
'আল্লাহুম্মা ইন্নি লাকা সুমতু ওয়া বিকা আমানতু ওয়া আলাইকা তাওয়াক্কালতু ওয়া আলা রিযক্বিকা আফতারতু',
'Allahumma inni laka sumtu wa bika amantu wa ''alayka tawakkaltu wa ''ala rizqika aftartu',
'হে আল্লাহ! আমি তোমার জন্য রোজা রেখেছি, তোমার উপর ঈমান এনেছি, তোমার উপর ভরসা করেছি এবং তোমার দেওয়া রিযিক দিয়ে ইফতার করছি',
'O Allah, for You I have fasted, in You I have believed, upon You I have relied, and with Your provision I break my fast',
'আবু দাউদ',
'Abu Dawud',
'রোজার পূর্ণতা, আল্লাহর নৈকট্য',
'Completion of fast, nearness to Allah',
17),

('লাইলাতুল কদরের দোয়া', 'Night of Decree', 'دُعَاءُ لَيْلَةِ الْقَدْرِ', 'রমজান', 'Ramadan',
'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
'আল্লাহুম্মা ইন্নাকা আফুওউন তুহিব্বুল আফওয়া ফা''ফু আন্নি',
'Allahumma innaka ''afuwwun tuhibbul-''afwa fa''fu ''anni',
'হে আল্লাহ! নিশ্চয় তুমি ক্ষমাশীল, ক্ষমা করতে ভালোবাসো, তাই আমাকে ক্ষমা করে দাও',
'O Allah, You are Most Forgiving, You love to forgive, so forgive me',
'তিরমিযী, ইবনে মাজাহ',
'Tirmidhi, Ibn Majah',
'লাইলাতুল কদরে সর্বোত্তম দোয়া, পূর্ণ ক্ষমা',
'Best dua for Laylatul Qadr, complete forgiveness',
18),

-- SPECIAL OCCASIONS
('সফরের দোয়া', 'Travel Dua', 'دُعَاءُ السَّفَرِ', 'বিশেষ সময়', 'Special Occasions',
'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
'সুবহানাল্লাযী সাখখারা লানা হাযা ওয়ামা কুন্না লাহু মুক্বরিনীন ওয়া ইন্না ইলা রাব্বিনা লামুনক্বালিবূন',
'Subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrinin wa inna ila Rabbina lamunqalibun',
'পবিত্র তিনি যিনি এটিকে আমাদের বশীভূত করেছেন অথচ আমরা এটি নিয়ন্ত্রণে সক্ষম ছিলাম না এবং নিশ্চয় আমরা আমাদের রবের কাছে ফিরে যাব',
'Glory be to Him who has subjected this to us, and we could not have it ourselves, and to our Lord we shall surely return',
'তিরমিযী, সূরা যুখরুফ ৪৩:১৩-১৪',
'Tirmidhi, Surah Az-Zukhruf 43:13-14',
'নিরাপদ সফর, সকল বিপদ থেকে হেফাজত',
'Safe journey, protection from all dangers',
19),

('বিবাহের দোয়া', 'Marriage Dua', 'دُعَاءُ النِّكَاحِ', 'বিশেষ সময়', 'Special Occasions',
'بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
'বারাকাল্লাহু লাকা ওয়া বারাকা আলাইকা ওয়া জামাআ বাইনাকুমা ফি খাইর',
'Barakallahu laka wa baraka ''alayka wa jama''a baynakuma fi khayr',
'আল্লাহ তোমাকে বরকত দিন, তোমার উপর বরকত বর্ষণ করুন এবং তোমাদের উভয়কে কল্যাণে একত্রিত করুন',
'May Allah bless you, send blessings upon you, and unite you both in goodness',
'তিরমিযী, আবু দাউদ',
'Tirmidhi, Abu Dawud',
'বিবাহে বরকত, সুখী দাম্পত্য জীবন',
'Blessings in marriage, happy conjugal life',
20),

('অসুস্থের জন্য দোয়া', 'For the Sick', 'دُعَاءُ الْمَرِيضِ', 'বিশেষ সময়', 'Special Occasions',
'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ اشْفِ أَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ شِفَاءً لَا يُغَادِرُ سَقَمًا',
'আল্লাহুম্মা রাব্বান নাসি আযহিবিল বা''সা ইশফি আনতাশ শাফী লা শিফাআ ইল্লা শিফাউকা শিফাআন লা ইউগাদিরু সাক্বামা',
'Allahumma Rabban-nasi adhhibil-ba''sa ishfi Antash-Shafi la shifa''a illa shifa''uka shifaan la yughadiru saqama',
'হে আল্লাহ! মানুষের রব! কষ্ট দূর করে দাও, আরোগ্য দান করো। তুমিই আরোগ্যদাতা। তোমার আরোগ্য ছাড়া কোন আরোগ্য নেই। এমন আরোগ্য যা কোন রোগ রেখে যায় না',
'O Allah, Lord of mankind, remove the hardship, and grant cure. You are the Healer, there is no healing except Your healing, a healing that leaves no illness',
'সহীহ বুখারী, সহীহ মুসলিম',
'Sahih Bukhari, Sahih Muslim',
'রোগ মুক্তি, দ্রুত আরোগ্য লাভ',
'Relief from illness, quick recovery',
21);

-- Verify insertion
SELECT category_english, COUNT(*) as total_duas 
FROM duas 
GROUP BY category_english 
ORDER BY category_english;
