-- Noor e Ramadan - Quran Surahs Seed Data
-- All 114 Surahs with complete metadata
-- Execute this in Supabase SQL Editor after running schema.sql

INSERT INTO quran_surahs (id, number, name_arabic, name_bangla, name_english, name_transliteration, revelation_type, revelation_type_bangla, total_ayahs, description_bangla, description_english) VALUES
(1, 1, 'الفَاتِحَة', 'আল-ফাতিহা', 'The Opening', 'Al-Fatihah', 'Meccan', 'মক্কী', 7, 'কুরআনের প্রথম সূরা। প্রতিটি নামাজে পাঠ করা হয়। আল্লাহর প্রশংসা ও সঠিক পথের প্রার্থনা রয়েছে।', 'The opening chapter of the Quran, recited in every prayer. Contains praise of Allah and prayer for guidance.'),
(2, 2, 'البَقَرَة', 'আল-বাকারা', 'The Cow', 'Al-Baqarah', 'Medinan', 'মাদানী', 286, 'কুরআনের সবচেয়ে দীর্ঘ সূরা। ঈমান, শরীয়ত, ইবাদাত ও জীবনবিধান নিয়ে আলোচনা রয়েছে। আয়াতুল কুরসী এই সূরায় আছে।', 'The longest chapter of the Quran. Discusses faith, law, worship, and way of life. Contains Ayatul Kursi.'),
(3, 3, 'آل عِمرَان', 'আলে-ইমরান', 'The Family of Imran', 'Ali Imran', 'Medinan', 'মাদানী', 200, 'ঈসা (আ) ও মরিয়ম (আ) এর কাহিনী বর্ণিত হয়েছে। ঈমান ও ধৈর্যের শিক্ষা রয়েছে।', 'Narrates the story of Jesus and Mary. Contains lessons on faith and patience.'),
(4, 4, 'النِّسَاء', 'আন-নিসা', 'The Women', 'An-Nisa', 'Medinan', 'মাদানী', 176, 'নারীদের অধিকার, পারিবারিক আইন, উত্তরাধিকার ও সামাজিক নিয়মকানুন নিয়ে আলোচনা।', 'Discusses women''s rights, family law, inheritance, and social regulations.'),
(5, 5, 'المَائدة', 'আল-মায়িদা', 'The Table Spread', 'Al-Maidah', 'Medinan', 'মাদানী', 120, 'খাদ্য বিধান, চুক্তি পালন ও ইসলামী আইন নিয়ে আলোচনা। ঈসা (আ) এর মুজিজা বর্ণিত।', 'Discusses dietary laws, fulfilling contracts, and Islamic law. Mentions miracles of Jesus.'),
(6, 6, 'الأنعَام', 'আল-আনআম', 'The Cattle', 'Al-Anam', 'Meccan', 'মক্কী', 165, 'তাওহীদ ও একত্ববাদের শক্তিশালী প্রমাণ। শিরক থেকে সতর্কতা।', 'Strong evidence of Tawhid and monotheism. Warning against shirk.'),
(7, 7, 'الأعرَاف', 'আল-আরাফ', 'The Heights', 'Al-Araf', 'Meccan', 'মক্কী', 206, 'নবীদের কাহিনী ও তাদের জাতির পরিণতি। জান্নাত ও জাহান্নামের বর্ণনা।', 'Stories of prophets and fate of their nations. Description of Paradise and Hell.'),
(8, 8, 'الأنفَال', 'আল-আনফাল', 'The Spoils of War', 'Al-Anfal', 'Medinan', 'মাদানী', 75, 'বদর যুদ্ধের শিক্ষা। যুদ্ধের নিয়মকানুন ও গনীমতের বিধান।', 'Lessons from Battle of Badr. Rules of war and distribution of spoils.'),
(9, 9, 'التوبَة', 'আত-তাওবা', 'The Repentance', 'At-Tawbah', 'Medinan', 'মাদানী', 129, 'তওবা, মুনাফিক ও কাফিরদের বিষয়ে। জিহাদ ও ত্যাগের গুরুত্ব।', 'Discusses repentance, hypocrites and disbelievers. Importance of jihad and sacrifice.'),
(10, 10, 'يُونس', 'ইউনুস', 'Jonah', 'Yunus', 'Meccan', 'মক্কী', 109, 'ইউনুস (আ) এর কাহিনী। তাওহীদ ও কুরআনের সত্যতা।', 'Story of Prophet Jonah. Tawhid and truthfulness of Quran.'),
(11, 11, 'هُود', 'হুদ', 'Hud', 'Hud', 'Meccan', 'মক্কী', 123, 'হুদ (আ) সহ বিভিন্ন নবীর কাহিনী। ধৈর্য ও দৃঢ়তার শিক্ষা।', 'Stories of Prophet Hud and other prophets. Lessons on patience and steadfastness.'),
(12, 12, 'يُوسُف', 'ইউসুফ', 'Joseph', 'Yusuf', 'Meccan', 'মক্কী', 111, 'ইউসুফ (আ) এর সম্পূর্ণ জীবনী। ধৈর্য, ক্ষমা ও আল্লাহর পরিকল্পনার সুন্দর উদাহরণ।', 'Complete biography of Prophet Joseph. Beautiful example of patience, forgiveness and Allah''s plan.'),
(13, 13, 'الرَّعْد', 'আর-রাদ', 'The Thunder', 'Ar-Rad', 'Medinan', 'মাদানী', 43, 'আল্লাহর নিদর্শন ও প্রকৃতির মধ্যে তাঁর শক্তির প্রমাণ।', 'Signs of Allah and proof of His power in nature.'),
(14, 14, 'إبراهيم', 'ইবরাহীম', 'Abraham', 'Ibrahim', 'Meccan', 'মক্কী', 52, 'ইবরাহীম (আ) এর দোয়া। সত্য ও মিথ্যার উপমা।', 'Prayer of Prophet Abraham. Parable of truth and falsehood.'),
(15, 15, 'الحِجر', 'আল-হিজর', 'The Rocky Tract', 'Al-Hijr', 'Meccan', 'মক্কী', 99, 'কুরআন সংরক্ষণের প্রতিশ্রুতি। অতীত জাতির পরিণতি।', 'Promise of Quran''s preservation. Fate of past nations.'),
(16, 16, 'النَّحل', 'আন-নাহল', 'The Bee', 'An-Nahl', 'Meccan', 'মক্কী', 128, 'আল্লাহর নিয়ামত ও সৃষ্টির নিদর্শন। মৌমাছির উদাহরণ।', 'Blessings of Allah and signs in creation. Example of the bee.'),
(17, 17, 'الإسرَاء', 'আল-ইসরা', 'The Night Journey', 'Al-Isra', 'Meccan', 'মক্কী', 111, 'মিরাজের বর্ণনা। মানবিক মূল্যবোধ ও নৈতিকতা।', 'Description of the Night Journey. Human values and morality.'),
(18, 18, 'الكهف', 'আল-কাহফ', 'The Cave', 'Al-Kahf', 'Meccan', 'মক্কী', 110, 'গুহার যুবকদের কাহিনী। জুমার দিন পাঠ করার ফজিলত রয়েছে।', 'Story of the people of the cave. Recommended to recite on Fridays.'),
(19, 19, 'مَريَم', 'মারইয়াম', 'Mary', 'Maryam', 'Meccan', 'মক্কী', 98, 'মরিয়ম (আ) ও ঈসা (আ) এর জন্ম কাহিনী। আল্লাহর কুদরত।', 'Story of Mary and birth of Jesus. Power of Allah.'),
(20, 20, 'طه', 'ত্বা-হা', 'Ta-Ha', 'Ta-Ha', 'Meccan', 'মক্কী', 135, 'মুসা (আ) ও ফেরাউনের কাহিনী। কুরআন অবতরণের উদ্দেশ্য।', 'Story of Moses and Pharaoh. Purpose of Quran''s revelation.'),
(21, 21, 'الأنبيَاء', 'আল-আম্বিয়া', 'The Prophets', 'Al-Anbiya', 'Meccan', 'মক্কী', 112, 'একাধিক নবীর সংক্ষিপ্ত কাহিনী। সবার বাণী এক - তাওহীদ।', 'Brief stories of multiple prophets. Their message is one - Tawhid.'),
(22, 22, 'الحَج', 'আল-হজ্জ', 'The Pilgrimage', 'Al-Hajj', 'Medinan', 'মাদানী', 78, 'হজের বিধান ও ইতিহাস। ইবরাহীম (আ) এর ত্যাগ।', 'Rules and history of Hajj. Sacrifice of Prophet Abraham.'),
(23, 23, 'المؤمنون', 'আল-মুমিনুন', 'The Believers', 'Al-Muminun', 'Meccan', 'মক্কী', 118, 'মুমিনদের গুণাবলী ও তাদের পুরস্কার।', 'Qualities of believers and their reward.'),
(24, 24, 'النُّور', 'আন-নূর', 'The Light', 'An-Nur', 'Medinan', 'মাদানী', 64, 'পর্দা, লজ্জা ও সামাজিক শিষ্টাচার। আয়াতুন নূর রয়েছে।', 'Hijab, modesty and social etiquette. Contains Ayat an-Nur.'),
(25, 25, 'الفُرقان', 'আল-ফুরকান', 'The Criterion', 'Al-Furqan', 'Meccan', 'মক্কী', 77, 'কুরআন - সত্য ও মিথ্যার মাপকাঠি। রহমানের বান্দাদের গুণ।', 'Quran - the criterion between truth and falsehood. Qualities of servants of the Most Merciful.'),
(26, 26, 'الشُّعَرَاء', 'আশ-শুআরা', 'The Poets', 'Ash-Shuara', 'Meccan', 'মক্কী', 227, 'নবীদের সংগ্রাম ও তাদের জাতির প্রতিক্রিয়া।', 'Struggle of prophets and reaction of their people.'),
(27, 27, 'النَّمل', 'আন-নাম্‌ল', 'The Ant', 'An-Naml', 'Meccan', 'মক্কী', 93, 'সুলায়মান (আ) ও বিলকিসের কাহিনী। পিঁপড়ার ঘটনা।', 'Story of Solomon and the Queen of Sheba. Incident of the ant.'),
(28, 28, 'القَصَص', 'আল-কাসাস', 'The Stories', 'Al-Qasas', 'Meccan', 'মক্কী', 88, 'মুসা (আ) এর জীবনের বিস্তারিত কাহিনী।', 'Detailed story of Prophet Moses'' life.'),
(29, 29, 'العَنكبوت', 'আল-আনকাবূত', 'The Spider', 'Al-Ankabut', 'Meccan', 'মক্কী', 69, 'ঈমান পরীক্ষা। মাকড়সার জালের উপমা।', 'Test of faith. Parable of the spider''s web.'),
(30, 30, 'الرُّوم', 'আর-রূম', 'The Romans', 'Ar-Rum', 'Meccan', 'মক্কী', 60, 'রোমানদের ভবিষ্যদ্বাণী। আল্লাহর নিদর্শন।', 'Prophecy about the Romans. Signs of Allah.'),
(31, 31, 'لقمَان', 'লুকমান', 'Luqman', 'Luqman', 'Meccan', 'মক্কী', 34, 'লুকমানের প্রজ্ঞাপূর্ণ উপদেশ তার সন্তানকে।', 'Wise advice of Luqman to his son.'),
(32, 32, 'السَّجدَة', 'আস-সাজদাহ', 'The Prostration', 'As-Sajdah', 'Meccan', 'মক্কী', 30, 'সৃষ্টি ও পুনরুত্থান। ফজরের নামাজে পাঠের সুন্নাত।', 'Creation and resurrection. Sunnah to recite in Fajr prayer.'),
(33, 33, 'الأحزَاب', 'আল-আহযাব', 'The Combined Forces', 'Al-Ahzab', 'Medinan', 'মাদানী', 73, 'খন্দকের যুদ্ধ। নবীজির পরিবার ও পর্দার বিধান।', 'Battle of the Trench. Prophet''s family and rules of hijab.'),
(34, 34, 'سَبَأ', 'সাবা', 'Sheba', 'Saba', 'Meccan', 'মক্কী', 54, 'সাবা জাতির কাহিনী। কৃতজ্ঞতা ও অকৃতজ্ঞতা।', 'Story of people of Sheba. Gratitude and ingratitude.'),
(35, 35, 'فَاطِر', 'ফাতির', 'The Originator', 'Fatir', 'Meccan', 'মক্কী', 45, 'আল্লাহ সৃষ্টিকর্তা। তাঁর সৃষ্টির বৈচিত্র্য।', 'Allah is the Originator. Diversity in His creation.'),
(36, 36, 'يس', 'ইয়াসীন', 'Ya-Sin', 'Ya-Sin', 'Meccan', 'মক্কী', 83, 'কুরআনের হৃদয়। পুনরুত্থান ও আখিরাতের প্রমাণ।', 'Heart of the Quran. Proof of resurrection and afterlife.'),
(37, 37, 'الصَّافات', 'আস-সাফফাত', 'Those Ranged in Ranks', 'As-Saffat', 'Meccan', 'মক্কী', 182, 'ফেরেশতারা। ইবরাহীম (আ) এর ত্যাগ।', 'Angels. Sacrifice of Prophet Abraham.'),
(38, 38, 'ص', 'সোয়াদ', 'The Letter Sad', 'Sad', 'Meccan', 'মক্কী', 88, 'দাউদ (আ) ও সুলায়মান (আ) এর কাহিনী।', 'Stories of Prophet David and Solomon.'),
(39, 39, 'الزُّمَر', 'আয-যুমার', 'The Groups', 'Az-Zumar', 'Meccan', 'মক্কী', 75, 'তওবা ও আল্লাহর রহমত। শিরক থেকে সতর্কতা।', 'Repentance and Allah''s mercy. Warning against shirk.'),
(40, 40, 'غَافِر', 'গাফির', 'The Forgiver', 'Ghafir', 'Meccan', 'মক্কী', 85, 'আল্লাহ ক্ষমাশীল। ফেরাউনের মুমিন আত্মীয়।', 'Allah is the Forgiver. Believer from Pharaoh''s family.'),
(41, 41, 'فُصِّلَت', 'ফুসসিলাত', 'Explained in Detail', 'Fussilat', 'Meccan', 'মক্কী', 54, 'কুরআনের বিস্তারিত ব্যাখ্যা। সেজদার আয়াত।', 'Detailed explanation of Quran. Contains verse of prostration.'),
(42, 42, 'الشُّورَى', 'আশ-শূরা', 'The Consultation', 'Ash-Shura', 'Meccan', 'মক্কী', 53, 'পরামর্শের গুরুত্ব। ওহীর প্রকৃতি।', 'Importance of consultation. Nature of revelation.'),
(43, 43, 'الزُّخرُف', 'আয-যুখরুফ', 'The Gold Adornments', 'Az-Zukhruf', 'Meccan', 'মক্কী', 89, 'দুনিয়ার চাকচিক্যের অসারতা।', 'Vanity of worldly glitter.'),
(44, 44, 'الدخَان', 'আদ-দুখান', 'The Smoke', 'Ad-Dukhan', 'Meccan', 'মক্কী', 59, 'কিয়ামতের নিদর্শন। লাইলাতুল কদরের উল্লেখ।', 'Signs of the Day of Judgment. Mention of Laylatul Qadr.'),
(45, 45, 'الجَاثيَة', 'আল-জাসিয়া', 'The Kneeling', 'Al-Jathiyah', 'Meccan', 'মক্কী', 37, 'বিচার দিবসে সবাই হাঁটু গেড়ে বসবে।', 'Everyone will be kneeling on the Day of Judgment.'),
(46, 46, 'الأحقاف', 'আল-আহকাফ', 'The Wind-Curved Sandhills', 'Al-Ahqaf', 'Meccan', 'মক্কী', 35, 'আদ জাতির ধ্বংস। পিতামাতার প্রতি সদাচার।', 'Destruction of people of Ad. Kindness to parents.'),
(47, 47, 'محَمَّد', 'মুহাম্মাদ', 'Muhammad', 'Muhammad', 'Medinan', 'মাদানী', 38, 'যুদ্ধের নিয়মকানুন। মুনাফিকদের পরিচয়।', 'Rules of war. Characteristics of hypocrites.'),
(48, 48, 'الفَتح', 'আল-ফাতহ', 'The Victory', 'Al-Fath', 'Medinan', 'মাদানী', 29, 'হুদাইবিয়ার সন্ধি - স্পষ্ট বিজয়।', 'Treaty of Hudaybiyyah - the clear victory.'),
(49, 49, 'الحُجُرات', 'আল-হুজুরাত', 'The Rooms', 'Al-Hujurat', 'Medinan', 'মাদানী', 18, 'ইসলামী শিষ্টাচার ও মানবিক সম্পর্ক।', 'Islamic etiquette and human relations.'),
(50, 50, 'ق', 'ক্বাফ', 'The Letter Qaf', 'Qaf', 'Meccan', 'মক্কী', 45, 'পুনরুত্থান ও মৃত্যুর ফেরেশতা।', 'Resurrection and the angel of death.'),
(51, 51, 'الذَّاريَات', 'আয-যারিয়াত', 'The Scatterers', 'Adh-Dhariyat', 'Meccan', 'মক্কী', 60, 'সৃষ্টির উদ্দেশ্য - ইবাদত।', 'Purpose of creation - worship.'),
(52, 52, 'الطُّور', 'আত-তূর', 'The Mount', 'At-Tur', 'Meccan', 'মক্কী', 49, 'তূর পাহাড়ের শপথ। জান্নাতের বর্ণনা।', 'Oath by Mount Tur. Description of Paradise.'),
(53, 53, 'النَّجْم', 'আন-নাজম', 'The Star', 'An-Najm', 'Meccan', 'মক্কী', 62, 'মিরাজ। সেজদার আয়াত।', 'The Night Journey. Contains verse of prostration.'),
(54, 54, 'القَمَر', 'আল-কামার', 'The Moon', 'Al-Qamar', 'Meccan', 'মক্কী', 55, 'চাঁদ দ্বিখণ্ডিত হওয়া। কুরআন সহজ করা হয়েছে।', 'Splitting of the moon. Quran has been made easy.'),
(55, 55, 'الرَّحمن', 'আর-রাহমান', 'The Most Merciful', 'Ar-Rahman', 'Medinan', 'মাদানী', 78, 'আল্লাহর অসংখ্য নিয়ামত। জান্নাত ও জাহান্নাম।', 'Countless blessings of Allah. Paradise and Hell.'),
(56, 56, 'الوَاقِعَة', 'আল-ওয়াকিয়া', 'The Event', 'Al-Waqiah', 'Meccan', 'মক্কী', 96, 'কিয়ামত। তিন শ্রেণীর মানুষ।', 'The Day of Judgment. Three categories of people.'),
(57, 57, 'الحَديد', 'আল-হাদীদ', 'The Iron', 'Al-Hadid', 'Medinan', 'মাদানী', 29, 'লোহা ও আল্লাহর শক্তি। দান-সদকার গুরুত্ব।', 'Iron and Allah''s power. Importance of charity.'),
(58, 58, 'المجَادلة', 'আল-মুজাদালা', 'The Pleading Woman', 'Al-Mujadila', 'Medinan', 'মাদানী', 22, 'যিহারের বিধান। গোপন পরামর্শ নিষিদ্ধ।', 'Rules of Zihar. Forbidden secret counsels.'),
(59, 59, 'الحَشر', 'আল-হাশর', 'The Gathering', 'Al-Hashr', 'Medinan', 'মাদানী', 24, 'ইহুদিদের নির্বাসন। আল্লাহর সুন্দর নামসমূহ।', 'Exile of Jews. Beautiful names of Allah.'),
(60, 60, 'الممتَحنَة', 'আল-মুমতাহিনা', 'The Examined One', 'Al-Mumtahanah', 'Medinan', 'মাদানী', 13, 'বন্ধুত্ব ও শত্রুতা। ঈমান পরীক্ষা।', 'Friendship and enmity. Test of faith.'),
(61, 61, 'الصَّف', 'আস-সফ', 'The Ranks', 'As-Saff', 'Medinan', 'মাদানী', 14, 'জিহাদে সারিবদ্ধ হওয়া। ঈসা (আ) এর সুসংবাদ।', 'Standing in ranks for jihad. Good news from Jesus.'),
(62, 62, 'الجُمُعَة', 'আল-জুমুআ', 'Friday', 'Al-Jumuah', 'Medinan', 'মাদানী', 11, 'জুমার নামাজের বিধান।', 'Rules of Friday prayer.'),
(63, 63, 'المنَافقون', 'আল-মুনাফিকূন', 'The Hypocrites', 'Al-Munafiqun', 'Medinan', 'মাদানী', 11, 'মুনাফিকদের চরিত্র ও পরিণতি।', 'Characteristics and fate of hypocrites.'),
(64, 64, 'التغَابن', 'আত-তাগাবুন', 'The Mutual Loss and Gain', 'At-Taghabun', 'Medinan', 'মাদানী', 18, 'ঈমান ও আমলের হিসাব।', 'Accounting of faith and deeds.'),
(65, 65, 'الطلاق', 'আত-তালাক', 'The Divorce', 'At-Talaq', 'Medinan', 'মাদানী', 12, 'তালাকের বিধান ও ইদ্দত।', 'Rules of divorce and waiting period.'),
(66, 66, 'التحْريم', 'আত-তাহরীম', 'The Prohibition', 'At-Tahrim', 'Medinan', 'মাদানী', 12, 'নবীজির ব্যক্তিগত জীবন। ফেরাউনের স্ত্রী ও মরিয়মের উদাহরণ।', 'Prophet''s personal life. Example of Pharaoh''s wife and Mary.'),
(67, 67, 'المُلك', 'আল-মুলক', 'The Sovereignty', 'Al-Mulk', 'Meccan', 'মক্কী', 30, 'আল্লাহর রাজত্ব। শয়নকালে পাঠের ফজিলত।', 'Sovereignty of Allah. Virtue of reciting before sleep.'),
(68, 68, 'القَلَم', 'আল-ক্বলম', 'The Pen', 'Al-Qalam', 'Meccan', 'মক্কী', 52, 'কলমের শপথ। নবীজির মহান চরিত্র।', 'Oath by the pen. Noble character of the Prophet.'),
(69, 69, 'الحَاقّة', 'আল-হাক্কা', 'The Inevitable', 'Al-Haqqah', 'Meccan', 'মক্কী', 52, 'কিয়ামত অবশ্যম্ভাবী। হিসাবের দিন।', 'The Day of Judgment is inevitable. Day of reckoning.'),
(70, 70, 'المعَارج', 'আল-মাআরিজ', 'The Ascending Stairways', 'Al-Maarij', 'Meccan', 'মক্কী', 44, 'ঊর্ধ্বগমনের সিঁড়ি। মুমিনদের গুণাবলী।', 'Ascending stairways. Qualities of believers.'),
(71, 71, 'نُوح', 'নূহ', 'Noah', 'Nuh', 'Meccan', 'মক্কী', 28, 'নুহ (আ) এর দীর্ঘ দাওয়াত ও মহাপ্লাবন।', 'Long call of Prophet Noah and the great flood.'),
(72, 72, 'الجِن', 'আল-জিন', 'The Jinn', 'Al-Jinn', 'Meccan', 'মক্কী', 28, 'জিনদের ঈমান। গায়েবের জ্ঞান।', 'Belief of the Jinn. Knowledge of the unseen.'),
(73, 73, 'المُزَّمّل', 'আল-মুযযাম্মিল', 'The Enshrouded One', 'Al-Muzzammil', 'Meccan', 'মক্কী', 20, 'রাতের নামাজের নির্দেশ। কুরআন তিলাওয়াত।', 'Command for night prayer. Recitation of Quran.'),
(74, 74, 'المُدَّثِّر', 'আল-মুদ্দাসসির', 'The Cloaked One', 'Al-Muddaththir', 'Meccan', 'মক্কী', 56, 'সতর্ককারী হিসেবে নবীজির দায়িত্ব।', 'Prophet''s duty as a warner.'),
(75, 75, 'القِيَامَة', 'আল-কিয়ামাহ', 'The Resurrection', 'Al-Qiyamah', 'Meccan', 'মক্কী', 40, 'কিয়ামত দিবস ও পুনরুত্থান।', 'Day of Resurrection.'),
(76, 76, 'الإنسَان', 'আল-ইনসান', 'The Human', 'Al-Insan', 'Medinan', 'মাদানী', 31, 'মানুষের সৃষ্টি। নেককারদের পুরস্কার।', 'Creation of man. Reward of the righteous.'),
(77, 77, 'المُرسَلات', 'আল-মুরসালাত', 'Those Sent Forth', 'Al-Mursalat', 'Meccan', 'মক্কী', 50, 'বাতাস ও ফেরেশতা। কিয়ামতের ভয়াবহতা।', 'Winds and angels. Terror of the Day of Judgment.'),
(78, 78, 'النَّبَإ', 'আন-নাবা', 'The Great News', 'An-Naba', 'Meccan', 'মক্কী', 40, 'মহাসংবাদ - কিয়ামত।', 'The great news - Day of Judgment.'),
(79, 79, 'النّازعَات', 'আন-নাযিআত', 'Those Who Pull Out', 'An-Naziat', 'Meccan', 'মক্কী', 46, 'মৃত্যুর ফেরেশতা। মুসা ও ফেরাউন।', 'Angel of death. Moses and Pharaoh.'),
(80, 80, 'عَبَسَ', 'আবাসা', 'He Frowned', 'Abasa', 'Meccan', 'মক্কী', 42, 'অন্ধ সাহাবীর ঘটনা। কুরআনের মর্যাদা।', 'Incident of the blind companion. Dignity of Quran.'),
(81, 81, 'التَّكوير', 'আত-তাকবীর', 'The Overthrowing', 'At-Takwir', 'Meccan', 'মক্কী', 29, 'কিয়ামতের নিদর্শন।', 'Signs of the Day of Judgment.'),
(82, 82, 'الانفِطار', 'আল-ইনফিতার', 'The Cleaving', 'Al-Infitar', 'Meccan', 'মক্কী', 19, 'আকাশ বিদীর্ণ হওয়া। কেরামান কাতিবীন।', 'Splitting of the sky. Honorable scribes (recording angels).'),
(83, 83, 'المطفِّفين', 'আল-মুতাফফিফীন', 'Those Who Deal in Fraud', 'Al-Mutaffifin', 'Meccan', 'মক্কী', 36, 'মাপে কম দেওয়া নিষিদ্ধ। হিসাবের দিন।', 'Forbidden to give less in measure. Day of reckoning.'),
(84, 84, 'الانشِقاق', 'আল-ইনশিকাক', 'The Splitting Asunder', 'Al-Inshiqaq', 'Meccan', 'মক্কী', 25, 'আকাশ বিদীর্ণ হবে। আমলনামা।', 'The sky will split. Record of deeds.'),
(85, 85, 'البرُوج', 'আল-বুরূজ', 'The Mansions of the Stars', 'Al-Buruj', 'Meccan', 'মক্কী', 22, 'নক্ষত্রমণ্ডল। খন্দকের অগ্নিতে নিক্ষিপ্ত ঈমানদারদের কাহিনী।', 'Constellations. Story of believers thrown into fire in the trench.'),
(86, 86, 'الطَّارِق', 'আত-তারিক', 'The Night-Comer', 'At-Tariq', 'Meccan', 'মক্কী', 17, 'রাতের আগন্তুক তারকা। মানুষের সৃষ্টি।', 'The night-comer star. Creation of man.'),
(87, 87, 'الأعلى', 'আল-আলা', 'The Most High', 'Al-Ala', 'Meccan', 'মক্কী', 19, 'মহান আল্লাহর তাসবীহ। তাকওয়ার উপদেশ।', 'Glorification of the Most High. Advice on piety.'),
(88, 88, 'الغَاشِيَة', 'আল-গাশিয়া', 'The Overwhelming', 'Al-Ghashiyah', 'Meccan', 'মক্কী', 26, 'আচ্ছাদনকারী ঘটনা - কিয়ামত।', 'The Overwhelming Event - Day of Judgment.'),
(89, 89, 'الفَجْر', 'আল-ফজর', 'The Dawn', 'Al-Fajr', 'Meccan', 'মক্কী', 30, 'ফজরের শপথ। অতীত জাতির ধ্বংস।', 'Oath by the dawn. Destruction of past nations.'),
(90, 90, 'البَلَد', 'আল-বালাদ', 'The City', 'Al-Balad', 'Meccan', 'মক্কী', 20, 'মক্কার শপথ। কষ্টের পথ অতিক্রম।', 'Oath by the city (Makkah). Overcoming hardship.'),
(91, 91, 'الشَّمْس', 'আশ-শামস', 'The Sun', 'Ash-Shams', 'Meccan', 'মক্কী', 15, 'সূর্যের শপথ। আত্মশুদ্ধি।', 'Oath by the sun. Purification of the soul.'),
(92, 92, 'الليْل', 'আল-লাইল', 'The Night', 'Al-Lail', 'Meccan', 'মক্কী', 21, 'রাতের শপথ। দান ও তাকওয়া।', 'Oath by the night. Charity and piety.'),
(93, 93, 'الضُّحَى', 'আদ-দুহা', 'The Forenoon', 'Ad-Duha', 'Meccan', 'মক্কী', 11, 'চাশতের শপথ। নবীজিকে সান্ত্বনা।', 'Oath by the forenoon. Consolation to the Prophet.'),
(94, 94, 'الشَّرْح', 'আশ-শারহ', 'The Opening Forth', 'Ash-Sharh', 'Meccan', 'মক্কী', 8, 'হৃদয় প্রশস্ত করা। কষ্টের সাথে স্বস্তি।', 'Expansion of the breast. With hardship comes ease.'),
(95, 95, 'التِّين', 'আত-ত্বীন', 'The Fig', 'At-Tin', 'Meccan', 'মক্কী', 8, 'ডুমুর ও জয়তুনের শপথ। সুন্দরতম সৃষ্টি।', 'Oath by the fig and olive. Best creation.'),
(96, 96, 'العَلَق', 'আল-আলাক', 'The Clot', 'Al-Alaq', 'Meccan', 'মক্কী', 19, 'প্রথম অবতীর্ণ আয়াত। "পড়ো"।', 'First revealed verses. "Read".'),
(97, 97, 'القَدْر', 'আল-ক্বদর', 'The Night of Decree', 'Al-Qadr', 'Meccan', 'মক্কী', 5, 'লাইলাতুল কদর। হাজার মাসের চেয়ে উত্তম।', 'The Night of Decree. Better than a thousand months.'),
(98, 98, 'البَيِّنَة', 'আল-বাইয়্যিনা', 'The Clear Evidence', 'Al-Bayyinah', 'Medinan', 'মাদানী', 8, 'সুস্পষ্ট প্রমাণ। সৃষ্টির শ্রেষ্ঠ মানুষ।', 'Clear evidence. Best of creatures.'),
(99, 99, 'الزلزَلة', 'আয-যিলযাল', 'The Earthquake', 'Az-Zalzalah', 'Medinan', 'মাদানী', 8, 'কিয়ামতের ভূমিকম্প। অণু পরিমাণ আমল।', 'Earthquake of the Hour. Atom''s weight of deeds.'),
(100, 100, 'العَاديَات', 'আল-আদিয়াত', 'Those That Run', 'Al-Adiyat', 'Meccan', 'মক্কী', 11, 'দৌড়ন্ত ঘোড়া। ধন-সম্পদের মোহ।', 'Running horses. Love of wealth.'),
(101, 101, 'القَارعَة', 'আল-কারিআহ', 'The Striking Hour', 'Al-Qariah', 'Meccan', 'মক্কী', 11, 'ভয়ংকর আঘাত - কিয়ামত।', 'The Striking Hour - Day of Judgment.'),
(102, 102, 'التَّكَاثر', 'আত-তাকাসুর', 'The Piling Up', 'At-Takathur', 'Meccan', 'মক্কী', 8, 'প্রাচুর্য্যের প্রতিযোগিতা। কবরের সফর।', 'Competition in accumulation. Visit to graves.'),
(103, 103, 'العَصْر', 'আল-আসর', 'The Time', 'Al-Asr', 'Meccan', 'মক্কী', 3, 'সময়ের শপথ। ঈমান ও সৎকর্মের গুরুত্ব।', 'Oath by time. Importance of faith and good deeds.'),
(104, 104, 'الهُمَزَة', 'আল-হুমাযাহ', 'The Slanderer', 'Al-Humazah', 'Meccan', 'মক্কী', 9, 'পশ্চাদ্গাত্রা ও নিন্দুক। সম্পদের অহংকার।', 'The slanderer and backbiter. Pride in wealth.'),
(105, 105, 'الفِيل', 'আল-ফীল', 'The Elephant', 'Al-Fil', 'Meccan', 'মক্কী', 5, 'হাতি বাহিনীর ঘটনা। কাবা রক্ষা।', 'Incident of the elephant. Protection of Kaaba.'),
(106, 106, 'قُرَيْش', 'কুরাইশ', 'Quraysh', 'Quraysh', 'Meccan', 'মক্কী', 4, 'কুরাইশদের নিরাপত্তা ও বাণিজ্য।', 'Security and trade of Quraysh.'),
(107, 107, 'المَاعُون', 'আল-মাউন', 'The Small Kindnesses', 'Al-Maun', 'Meccan', 'মক্কী', 7, 'ছোট সাহায্য। লোক দেখানো নামাজ।', 'Small kindnesses. Prayer for show.'),
(108, 108, 'الكَوْثَر', 'আল-কাউসার', 'The Abundance', 'Al-Kawthar', 'Meccan', 'মক্কী', 3, 'কাউসার ঝর্ণা। কুরবানী ও নামাজ।', 'Fountain of Kawthar. Sacrifice and prayer.'),
(109, 109, 'الكَافِرُون', 'আল-কাফিরুন', 'The Disbelievers', 'Al-Kafirun', 'Meccan', 'মক্কী', 6, 'দ্বীনে কোন আপস নেই।', 'No compromise in religion.'),
(110, 110, 'النَّصر', 'আন-নাসর', 'The Divine Support', 'An-Nasr', 'Medinan', 'মাদানী', 3, 'আল্লাহর সাহায্য ও বিজয়। তাসবীহ।', 'Allah''s help and victory. Glorification.'),
(111, 111, 'المَسَد', 'আল-মাসাদ', 'The Palm Fiber', 'Al-Masad', 'Meccan', 'মক্কী', 5, 'আবু লাহাবের শাস্তি।', 'Punishment of Abu Lahab.'),
(112, 112, 'الإخْلَاص', 'আল-ইখলাস', 'The Sincerity', 'Al-Ikhlas', 'Meccan', 'মক্কী', 4, 'তাওহীদ। কুরআনের এক তৃতীয়াংশের সমান।', 'Tawhid. Equivalent to one-third of Quran.'),
(113, 113, 'الفَلَق', 'আল-ফালাক', 'The Daybreak', 'Al-Falaq', 'Meccan', 'মক্কী', 5, 'সকালের আলোর রব। সকল অনিষ্ট থেকে আশ্রয়।', 'Lord of the daybreak. Refuge from all evils.'),
(114, 114, 'النَّاس', 'আন-নাস', 'The Mankind', 'An-Nas', 'Meccan', 'মক্কী', 6, 'মানুষের রব। ওয়াসওয়াসা থেকে আশ্রয়।', 'Lord of mankind. Refuge from whispers.')
ON CONFLICT (id) DO NOTHING;

-- Verify insertion
SELECT COUNT(*) as total_surahs FROM quran_surahs;
